eureka:
  client:
    serviceUrl:
      defaultZone: http://${DISCOVERY_SERVER_HOST:localhost}:${DISCOVERY_SERVER_PORT:8761}/eureka/
  instance:
    preferIpAddress: true

spring:
   zipkin:
      baseUrl: http://localhost:9411
   sleuth:
     sampler:
       percentage: 1.0
       
# disable actuator security
management:
  security:
    enabled: false